// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/easayliu/alist-aria2-download/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alist/file": {
            "get": {
                "description": "获取Alist中指定路径文件的详细信息，包含下载链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alist管理"
                ],
                "summary": "获取文件信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件完整路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件详细信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/alist/files": {
            "get": {
                "description": "获取Alist中指定路径的文件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alist管理"
                ],
                "summary": "获取文件列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件路径（留空使用配置的默认路径）",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/alist/login": {
            "post": {
                "description": "使用配置文件中的用户名密码登录Alist服务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alist管理"
                ],
                "summary": "Alist登录",
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "登录失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads": {
            "get": {
                "description": "获取所有Aria2下载任务列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "获取下载列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的Aria2下载任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "创建下载任务",
                "parameters": [
                    {
                        "description": "下载请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.DownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载任务创建成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/batch": {
            "post": {
                "description": "批量创建多个Aria2下载任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "批量创建下载任务",
                "parameters": [
                    {
                        "description": "批量下载请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.BatchDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批量下载任务创建成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/pause-all": {
            "post": {
                "description": "暂停所有正在进行的下载任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "暂停所有下载",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/resume-all": {
            "post": {
                "description": "恢复所有已暂停的下载任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "恢复所有下载",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/statistics": {
            "get": {
                "description": "获取下载任务的统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "获取下载统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/system-status": {
            "get": {
                "description": "获取Aria2系统的状态信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "获取系统状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/{id}": {
            "get": {
                "description": "根据GID获取单个下载任务详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "获取下载详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "下载任务GID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "根据GID删除下载任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "删除下载任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "下载任务GID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/{id}/pause": {
            "post": {
                "description": "暂停指定的下载任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "暂停下载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "下载任务GID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/downloads/{id}/resume": {
            "post": {
                "description": "恢复指定的下载任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "恢复下载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "下载任务GID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/category/{category}": {
            "get": {
                "description": "获取指定分类的文件列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "按分类获取文件",
                "parameters": [
                    {
                        "enum": [
                            "video",
                            "audio",
                            "image",
                            "document",
                            "archive",
                            "other"
                        ],
                        "type": "string",
                        "description": "文件分类",
                        "name": "category",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索路径",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分类文件列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/classify": {
            "post": {
                "description": "将文件列表按照类型进行分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "分类文件",
                "parameters": [
                    {
                        "description": "文件分类请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.FileClassificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分类结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/download": {
            "post": {
                "description": "获取指定路径下的所有文件并添加到Aria2下载队列，支持递归下载子目录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "从指定路径下载文件",
                "parameters": [
                    {
                        "description": "下载路径请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.DirectoryDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载任务创建结果或预览信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/list": {
            "post": {
                "description": "获取指定路径下的文件列表，支持分页和视频文件过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "列出指定路径的文件",
                "parameters": [
                    {
                        "description": "列出文件请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.FileListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/manual-download": {
            "post": {
                "description": "手动执行指定时间范围内的文件下载，支持预览模式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "手动执行文件下载",
                "parameters": [
                    {
                        "description": "下载参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.TimeRangeFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/recent": {
            "get": {
                "description": "获取最近指定小时内修改的文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取最近文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索路径",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "小时数",
                        "name": "hours_ago",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "最近文件列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/search": {
            "post": {
                "description": "在指定路径中搜索符合条件的文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "搜索文件",
                "parameters": [
                    {
                        "description": "搜索请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.FileSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "搜索结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/single-download": {
            "post": {
                "description": "下载指定路径的单个文件到Aria2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "下载单个文件",
                "parameters": [
                    {
                        "description": "文件下载请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.FileDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件下载任务创建成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/time-range": {
            "post": {
                "description": "获取指定时间范围内修改的文件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "按时间范围获取文件",
                "parameters": [
                    {
                        "description": "时间范围请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.TimeRangeFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "时间范围内的文件列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/yesterday": {
            "get": {
                "description": "获取昨天修改的文件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取昨天的文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索路径（留空使用配置的默认路径）",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "昨天的文件列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/yesterday/download": {
            "post": {
                "description": "将昨天修改的文件批量添加到Aria2下载队列",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "批量下载昨天文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索路径（留空使用配置的默认路径）",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "预览模式，只生成路径不下载",
                        "name": "preview",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载任务创建结果或预览信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务健康状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications/batch": {
            "post": {
                "description": "批量发送多个通知消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "批量发送通知",
                "parameters": [
                    {
                        "description": "批量通知请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.BatchNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批量通知发送结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/config": {
            "get": {
                "description": "获取通知系统的配置信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "获取通知配置",
                "responses": {
                    "200": {
                        "description": "通知配置信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/download-complete": {
            "post": {
                "description": "发送下载完成通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "下载完成通知",
                "parameters": [
                    {
                        "description": "下载通知请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.DownloadNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知发送成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/download-failed": {
            "post": {
                "description": "发送下载失败通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "下载失败通知",
                "parameters": [
                    {
                        "description": "下载通知请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.DownloadNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知发送成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/history": {
            "get": {
                "description": "获取历史通知记录列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "获取通知历史",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知历史列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/send": {
            "post": {
                "description": "发送单个通知消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "发送通知",
                "parameters": [
                    {
                        "description": "通知请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.NotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知发送成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/stats": {
            "get": {
                "description": "获取通知系统的统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "获取通知统计",
                "responses": {
                    "200": {
                        "description": "通知统计信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/system-event": {
            "post": {
                "description": "发送系统事件通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "系统事件通知",
                "parameters": [
                    {
                        "description": "系统通知请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.SystemNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知发送成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/task-complete": {
            "post": {
                "description": "发送任务完成通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "任务完成通知",
                "parameters": [
                    {
                        "description": "任务通知请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知发送成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/task-failed": {
            "post": {
                "description": "发送任务失败通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知管理"
                ],
                "summary": "任务失败通知",
                "parameters": [
                    {
                        "description": "任务通知请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知发送成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "获取所有定时任务的列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "获取定时任务列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "创建者ID",
                        "name": "created_by",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否启用",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序方向",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务列表",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskListResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的定时任务，按照cron表达式定期执行",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "创建定时任务",
                "parameters": [
                    {
                        "description": "创建任务请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务创建成功",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/quick": {
            "post": {
                "description": "创建预定义的快捷任务（每日、最近等）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "创建快捷任务",
                "parameters": [
                    {
                        "description": "快捷任务请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.QuickTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务创建成功",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/scheduler/status": {
            "get": {
                "description": "获取任务调度器的状态信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "获取调度器状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/statistics": {
            "get": {
                "description": "获取任务系统的统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "获取任务统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/user/{user-id}": {
            "get": {
                "description": "获取指定用户的所有任务列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "获取用户任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户任务列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "根据任务ID获取定时任务的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "获取定时任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务详情",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskResponse"
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定ID的定时任务信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "更新定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新任务请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务更新成功",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定ID的定时任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "删除定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{id}/disable": {
            "post": {
                "description": "禁用指定ID的定时任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "禁用定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务禁用成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{id}/enable": {
            "post": {
                "description": "启用指定ID的定时任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "启用定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务启用成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{id}/preview": {
            "get": {
                "description": "预览定时任务将要下载的文件，不实际执行下载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "预览定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "预览结果",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskPreviewResponse"
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{id}/run": {
            "post": {
                "description": "立即执行指定ID的定时任务，不等待下一个调度时间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "立即执行定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "执行选项",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskRunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务已开始执行或预览结果",
                        "schema": {
                            "$ref": "#/definitions/contracts.TaskRunResponse"
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{id}/stop": {
            "post": {
                "description": "停止正在运行的任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "停止任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务停止成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contracts.BatchDownloadRequest": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "auto_classify": {
                    "type": "boolean"
                },
                "directory": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.DownloadRequest"
                    }
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "contracts.BatchNotificationRequest": {
            "type": "object",
            "required": [
                "notifications"
            ],
            "properties": {
                "batch_mode": {
                    "description": "是否批量发送",
                    "type": "boolean"
                },
                "fail_fast": {
                    "description": "遇到错误是否立即停止",
                    "type": "boolean"
                },
                "notifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.NotificationRequest"
                    }
                }
            }
        },
        "contracts.DirectoryDownloadRequest": {
            "type": "object",
            "required": [
                "directory_path"
            ],
            "properties": {
                "auto_classify": {
                    "type": "boolean"
                },
                "directory_path": {
                    "type": "string"
                },
                "recursive": {
                    "type": "boolean"
                },
                "target_dir": {
                    "type": "string"
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "contracts.DownloadNotificationRequest": {
            "type": "object"
        },
        "contracts.DownloadRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "auto_classify": {
                    "type": "boolean"
                },
                "directory": {
                    "type": "string"
                },
                "file_size": {
                    "description": "文件大小，用于磁盘空间检查",
                    "type": "integer"
                },
                "filename": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "url": {
                    "type": "string"
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "contracts.FileClassificationRequest": {
            "type": "object",
            "required": [
                "files"
            ],
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.FileResponse"
                    }
                }
            }
        },
        "contracts.FileDownloadRequest": {
            "type": "object",
            "required": [
                "file_path"
            ],
            "properties": {
                "auto_classify": {
                    "type": "boolean"
                },
                "file_path": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "target_dir": {
                    "type": "string"
                }
            }
        },
        "contracts.FileListRequest": {
            "type": "object",
            "required": [
                "path"
            ],
            "properties": {
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "page_size": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                },
                "path": {
                    "type": "string"
                },
                "recursive": {
                    "type": "boolean"
                },
                "sort_by": {
                    "type": "string",
                    "enum": [
                        "name",
                        "size",
                        "modified"
                    ]
                },
                "sort_order": {
                    "type": "string",
                    "enum": [
                        "asc",
                        "desc"
                    ]
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "contracts.FilePreview": {
            "type": "object",
            "properties": {
                "download_path": {
                    "type": "string"
                },
                "internal_url": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "modified": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "contracts.FileResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "download_path": {
                    "type": "string"
                },
                "external_url": {
                    "type": "string"
                },
                "internal_url": {
                    "type": "string"
                },
                "is_dir": {
                    "type": "boolean"
                },
                "media_type": {
                    "type": "string"
                },
                "modified": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "size_formatted": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                }
            }
        },
        "contracts.FileSearchRequest": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "file_type": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer",
                    "maximum": 1000,
                    "minimum": 1
                },
                "max_size": {
                    "type": "integer"
                },
                "min_size": {
                    "type": "integer"
                },
                "modified_after": {
                    "type": "string"
                },
                "modified_before": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "contracts.NotificationChannel": {
            "type": "string",
            "enum": [
                "telegram",
                "webhook",
                "email",
                "system"
            ],
            "x-enum-varnames": [
                "ChannelTelegram",
                "ChannelWebhook",
                "ChannelEmail",
                "ChannelSystem"
            ]
        },
        "contracts.NotificationLevel": {
            "type": "string",
            "enum": [
                "info",
                "warning",
                "error",
                "success"
            ],
            "x-enum-varnames": [
                "NotificationLevelInfo",
                "NotificationLevelWarning",
                "NotificationLevelError",
                "NotificationLevelSuccess"
            ]
        },
        "contracts.NotificationRequest": {
            "type": "object",
            "required": [
                "channel",
                "level",
                "message",
                "title"
            ],
            "properties": {
                "channel": {
                    "$ref": "#/definitions/contracts.NotificationChannel"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "level": {
                    "$ref": "#/definitions/contracts.NotificationLevel"
                },
                "message": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "target_id": {
                    "description": "如Telegram chat_id",
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "contracts.PreviewSummary": {
            "type": "object",
            "properties": {
                "movie_files": {
                    "type": "integer"
                },
                "other_files": {
                    "type": "integer"
                },
                "total_files": {
                    "type": "integer"
                },
                "total_size": {
                    "type": "string"
                },
                "tv_files": {
                    "type": "integer"
                },
                "video_files": {
                    "type": "integer"
                }
            }
        },
        "contracts.QuickTaskRequest": {
            "type": "object",
            "required": [
                "created_by",
                "type"
            ],
            "properties": {
                "created_by": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "daily",
                        "recent",
                        "weekly",
                        "realtime"
                    ]
                }
            }
        },
        "contracts.SystemNotificationRequest": {
            "type": "object",
            "required": [
                "component",
                "event",
                "level",
                "message"
            ],
            "properties": {
                "component": {
                    "description": "aria2, alist, scheduler, etc.",
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "event": {
                    "description": "startup, shutdown, error, etc.",
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/contracts.NotificationLevel"
                },
                "message": {
                    "type": "string"
                },
                "metrics": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "contracts.TaskListResponse": {
            "type": "object",
            "properties": {
                "summary": {
                    "$ref": "#/definitions/contracts.TaskSummary"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.TaskResponse"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "contracts.TaskNotificationRequest": {
            "type": "object"
        },
        "contracts.TaskPreviewResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.FilePreview"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/contracts.PreviewSummary"
                },
                "task": {
                    "$ref": "#/definitions/contracts.TaskResponse"
                },
                "time_range": {
                    "$ref": "#/definitions/contracts.TimeRange"
                }
            }
        },
        "contracts.TaskRequest": {
            "type": "object",
            "required": [
                "cron_expr",
                "hours_ago",
                "name",
                "path"
            ],
            "properties": {
                "auto_preview": {
                    "type": "boolean"
                },
                "created_by": {
                    "type": "integer"
                },
                "cron_expr": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "hours_ago": {
                    "description": "最多1年",
                    "type": "integer",
                    "maximum": 8760,
                    "minimum": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "path": {
                    "type": "string"
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "contracts.TaskResponse": {
            "type": "object",
            "properties": {
                "auto_preview": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "cron_expr": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "failure_count": {
                    "type": "integer"
                },
                "hours_ago": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_run_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "next_run_at": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "run_count": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/entities.TaskStatus"
                },
                "success_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "contracts.TaskRunRequest": {
            "type": "object",
            "required": [
                "task_id"
            ],
            "properties": {
                "force_run": {
                    "type": "boolean"
                },
                "notify_user": {
                    "type": "boolean"
                },
                "preview": {
                    "type": "boolean"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "contracts.TaskRunResponse": {
            "type": "object",
            "properties": {
                "download_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preview": {
                    "$ref": "#/definitions/contracts.TaskPreviewResponse"
                },
                "run_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "contracts.TaskSummary": {
            "type": "object",
            "properties": {
                "disabled_count": {
                    "type": "integer"
                },
                "enabled_count": {
                    "type": "integer"
                },
                "error_count": {
                    "type": "integer"
                },
                "running_count": {
                    "type": "integer"
                }
            }
        },
        "contracts.TaskUpdateRequest": {
            "type": "object",
            "properties": {
                "auto_preview": {
                    "type": "boolean"
                },
                "cron_expr": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "hours_ago": {
                    "type": "integer",
                    "maximum": 8760,
                    "minimum": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "path": {
                    "type": "string"
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "contracts.TimeRange": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "contracts.TimeRangeFileRequest": {
            "type": "object",
            "required": [
                "end_time",
                "path",
                "start_time"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "hours_ago": {
                    "type": "integer",
                    "maximum": 8760,
                    "minimum": 1
                },
                "path": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "video_only": {
                    "type": "boolean"
                }
            }
        },
        "entities.TaskStatus": {
            "type": "string",
            "enum": [
                "idle",
                "running",
                "success",
                "error",
                "stopped"
            ],
            "x-enum-comments": {
                "TaskStatusError": "最后一次执行失败",
                "TaskStatusIdle": "空闲状态",
                "TaskStatusRunning": "运行中",
                "TaskStatusStopped": "已停止",
                "TaskStatusSuccess": "最后一次执行成功"
            },
            "x-enum-descriptions": [
                "空闲状态",
                "运行中",
                "最后一次执行成功",
                "最后一次执行失败",
                "已停止"
            ],
            "x-enum-varnames": [
                "TaskStatusIdle",
                "TaskStatusRunning",
                "TaskStatusSuccess",
                "TaskStatusError",
                "TaskStatusStopped"
            ]
        },
        "handlers.CreateDownloadRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "dir": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Alist Aria2 Download API",
	Description:      "基于Gin框架的Alist和Aria2下载管理服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
