basePath: /api/v1
definitions:
  handlers.CreateDownloadRequest:
    properties:
      dir:
        type: string
      filename:
        type: string
      options:
        additionalProperties: true
        type: object
      url:
        type: string
    required:
    - url
    type: object
  handlers.DownloadPathRequest:
    properties:
      path:
        type: string
      preview:
        description: 预览模式，只生成路径不下载
        type: boolean
      recursive:
        type: boolean
    required:
    - path
    type: object
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 基于Gin框架的Alist和Aria2下载管理服务
  license:
    name: MIT
    url: https://github.com/easayliu/alist-aria2-download/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Alist Aria2 Download API
  version: "1.0"
paths:
  /alist/file:
    get:
      consumes:
      - application/json
      description: 获取Alist中指定路径文件的详细信息，包含下载链接
      parameters:
      - description: 文件完整路径
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 文件详细信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取文件信息
      tags:
      - Alist管理
  /alist/files:
    get:
      consumes:
      - application/json
      description: 获取Alist中指定路径的文件列表，需要先调用登录接口。如果不传path参数，将使用配置文件中的默认路径
      parameters:
      - description: 文件路径（留空使用配置的默认路径）
        in: query
        name: path
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文件列表
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取文件列表
      tags:
      - Alist管理
  /alist/login:
    post:
      description: 使用配置文件中的用户名密码登录Alist服务
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 登录失败
          schema:
            additionalProperties: true
            type: object
      summary: Alist登录
      tags:
      - Alist管理
  /downloads:
    get:
      description: 获取所有Aria2下载任务列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 获取下载列表
      tags:
      - 下载管理
    post:
      consumes:
      - application/json
      description: 创建新的Aria2下载任务
      parameters:
      - description: 下载请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateDownloadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 下载任务创建成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 创建下载任务
      tags:
      - 下载管理
  /downloads/{id}:
    delete:
      description: 根据GID删除下载任务
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 删除下载任务
      tags:
      - 下载管理
    get:
      description: 根据GID获取单个下载任务详情
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 获取下载详情
      tags:
      - 下载管理
  /downloads/{id}/pause:
    post:
      description: 暂停指定的下载任务
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 暂停下载
      tags:
      - 下载管理
  /downloads/{id}/resume:
    post:
      description: 恢复指定的下载任务
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 恢复下载
      tags:
      - 下载管理
  /files/download:
    post:
      consumes:
      - application/json
      description: 获取指定路径下的所有文件并添加到Aria2下载队列，支持递归下载子目录，支持预览模式
      parameters:
      - description: 下载路径请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.DownloadPathRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 下载任务创建结果或预览信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 从指定路径下载文件
      tags:
      - 文件管理
  /files/yesterday:
    get:
      consumes:
      - application/json
      description: 批量获取昨天修改的文件信息，并将raw_url中的fcalist-public替换为fcalist-internal
      parameters:
      - description: 搜索路径（留空使用配置的默认路径）
        in: query
        name: path
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 昨天的文件列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取昨天的文件
      tags:
      - 文件管理
  /files/yesterday/download:
    post:
      consumes:
      - application/json
      description: 将昨天修改的文件批量添加到Aria2下载队列，使用内部URL，支持预览模式
      parameters:
      - description: 搜索路径（留空使用配置的默认路径）
        in: query
        name: path
        type: string
      - description: 预览模式，只生成路径不下载
        in: query
        name: preview
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 下载任务创建结果或预览信息
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 批量下载昨天文件
      tags:
      - 文件管理
  /health:
    get:
      description: 检查服务健康状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 健康检查
      tags:
      - 健康检查
schemes:
- http
- https
swagger: "2.0"
