basePath: /api/v1
definitions:
  entities.ScheduledTask:
    properties:
      auto_preview:
        description: 是否预览模式
        type: boolean
      created_at:
        description: 创建时间
        type: string
      created_by:
        description: 创建者Telegram ID
        type: integer
      cron:
        description: cron表达式
        type: string
      enabled:
        description: 是否启用
        type: boolean
      hours_ago:
        description: 下载多少小时内的文件
        type: integer
      id:
        description: 任务ID
        type: string
      last_run_at:
        description: 最后运行时间
        type: string
      name:
        description: 任务名称
        type: string
      next_run_at:
        description: 下次运行时间
        type: string
      path:
        description: 下载路径
        type: string
      updated_at:
        description: 更新时间
        type: string
      video_only:
        description: 是否只下载视频
        type: boolean
    type: object
  handlers.CreateDownloadRequest:
    properties:
      dir:
        type: string
      filename:
        type: string
      options:
        additionalProperties: true
        type: object
      url:
        type: string
    required:
    - url
    type: object
  handlers.CreateTaskRequest:
    properties:
      auto_preview:
        example: false
        type: boolean
      created_by:
        example: 63401853
        type: integer
      cron_expr:
        example: 0 2 * * *
        type: string
      enabled:
        example: true
        type: boolean
      hours_ago:
        example: 24
        minimum: 1
        type: integer
      name:
        example: 每日同步
        type: string
      path:
        example: /data/来自：分享
        type: string
      video_only:
        example: true
        type: boolean
    required:
    - cron_expr
    - hours_ago
    - name
    - path
    type: object
  handlers.DownloadPathRequest:
    properties:
      path:
        type: string
      preview:
        description: 预览模式，只生成路径不下载
        type: boolean
      recursive:
        type: boolean
    required:
    - path
    type: object
  handlers.FileListRequest:
    properties:
      page:
        type: integer
      path:
        description: 路径，为空时使用默认路径
        type: string
      per_page:
        type: integer
      video_only:
        description: 是否只显示视频文件
        type: boolean
    type: object
  handlers.ManualDownloadRequest:
    properties:
      end_time:
        description: 结束时间（可选，ISO 8601格式）
        example: "2023-12-02T00:00:00Z"
        type: string
      hours_ago:
        description: 最近多少小时内的文件（可选，默认24小时）
        example: 24
        type: integer
      path:
        description: 搜索路径（可选，为空时使用配置的默认路径）
        example: /downloads
        type: string
      preview:
        description: 是否预览模式
        example: false
        type: boolean
      start_time:
        description: 开始时间（可选，ISO 8601格式）
        example: "2023-12-01T00:00:00Z"
        type: string
      video_only:
        description: 是否只下载视频文件
        example: false
        type: boolean
    type: object
  handlers.RunTaskRequest:
    properties:
      preview:
        description: 是否仅预览，不实际下载
        example: false
        type: boolean
    type: object
  handlers.UpdateTaskRequest:
    properties:
      auto_preview:
        example: false
        type: boolean
      cron_expr:
        example: 0 2 * * *
        type: string
      enabled:
        example: true
        type: boolean
      hours_ago:
        example: 24
        type: integer
      name:
        example: 每日同步
        type: string
      path:
        example: /data/来自：分享
        type: string
      video_only:
        example: true
        type: boolean
    type: object
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 基于Gin框架的Alist和Aria2下载管理服务
  license:
    name: MIT
    url: https://github.com/easayliu/alist-aria2-download/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Alist Aria2 Download API
  version: "1.0"
paths:
  /alist/file:
    get:
      consumes:
      - application/json
      description: 获取Alist中指定路径文件的详细信息，包含下载链接
      parameters:
      - description: 文件完整路径
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 文件详细信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取文件信息
      tags:
      - Alist管理
  /alist/files:
    get:
      consumes:
      - application/json
      description: 获取Alist中指定路径的文件列表，需要先调用登录接口。如果不传path参数，将使用配置文件中的默认路径
      parameters:
      - description: 文件路径（留空使用配置的默认路径）
        in: query
        name: path
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文件列表
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取文件列表
      tags:
      - Alist管理
  /alist/login:
    post:
      description: 使用配置文件中的用户名密码登录Alist服务
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 登录失败
          schema:
            additionalProperties: true
            type: object
      summary: Alist登录
      tags:
      - Alist管理
  /downloads:
    get:
      description: 获取所有Aria2下载任务列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 获取下载列表
      tags:
      - 下载管理
    post:
      consumes:
      - application/json
      description: 创建新的Aria2下载任务
      parameters:
      - description: 下载请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateDownloadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 下载任务创建成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 创建下载任务
      tags:
      - 下载管理
  /downloads/{id}:
    delete:
      description: 根据GID删除下载任务
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 删除下载任务
      tags:
      - 下载管理
    get:
      description: 根据GID获取单个下载任务详情
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 获取下载详情
      tags:
      - 下载管理
  /downloads/{id}/pause:
    post:
      description: 暂停指定的下载任务
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 暂停下载
      tags:
      - 下载管理
  /downloads/{id}/resume:
    post:
      description: 恢复指定的下载任务
      parameters:
      - description: 下载任务GID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 恢复下载
      tags:
      - 下载管理
  /files/download:
    post:
      consumes:
      - application/json
      description: 获取指定路径下的所有文件并添加到Aria2下载队列，支持递归下载子目录，支持预览模式
      parameters:
      - description: 下载路径请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.DownloadPathRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 下载任务创建结果或预览信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 从指定路径下载文件
      tags:
      - 文件管理
  /files/list:
    post:
      consumes:
      - application/json
      description: 获取指定路径下的文件列表，支持分页和视频文件过滤
      parameters:
      - description: 列出文件请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.FileListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 文件列表
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 列出指定路径的文件
      tags:
      - 文件管理
  /files/manual-download:
    post:
      consumes:
      - application/json
      description: 手动执行指定时间范围内的文件下载，支持预览模式
      parameters:
      - description: 下载参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ManualDownloadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 下载结果
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 手动执行文件下载
      tags:
      - 文件管理
  /files/yesterday:
    get:
      consumes:
      - application/json
      description: 批量获取昨天修改的文件信息，并将raw_url中的fcalist-public替换为fcalist-internal
      parameters:
      - description: 搜索路径（留空使用配置的默认路径）
        in: query
        name: path
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 昨天的文件列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取昨天的文件
      tags:
      - 文件管理
  /files/yesterday/download:
    post:
      consumes:
      - application/json
      description: 将昨天修改的文件批量添加到Aria2下载队列，使用内部URL，支持预览模式
      parameters:
      - description: 搜索路径（留空使用配置的默认路径）
        in: query
        name: path
        type: string
      - description: 预览模式，只生成路径不下载
        in: query
        name: preview
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 下载任务创建结果或预览信息
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 批量下载昨天文件
      tags:
      - 文件管理
  /health:
    get:
      description: 检查服务健康状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 健康检查
      tags:
      - 健康检查
  /tasks:
    get:
      consumes:
      - application/json
      description: 获取所有定时任务的列表
      produces:
      - application/json
      responses:
        "200":
          description: 任务列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取定时任务列表
      tags:
      - 定时任务
    post:
      consumes:
      - application/json
      description: 创建一个新的定时任务，按照cron表达式定期执行
      parameters:
      - description: 创建任务请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 任务创建成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 创建定时任务
      tags:
      - 定时任务
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: 删除指定ID的定时任务
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 任务删除成功
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 任务不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 删除定时任务
      tags:
      - 定时任务
    get:
      consumes:
      - application/json
      description: 根据任务ID获取定时任务的详细信息
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 任务详情
          schema:
            $ref: '#/definitions/entities.ScheduledTask'
        "404":
          description: 任务不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取定时任务详情
      tags:
      - 定时任务
    put:
      consumes:
      - application/json
      description: 更新指定ID的定时任务信息
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新任务请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 任务更新成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 任务不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 更新定时任务
      tags:
      - 定时任务
  /tasks/{id}/preview:
    get:
      consumes:
      - application/json
      description: 预览定时任务将要下载的文件，不实际执行下载
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 预览结果
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 任务不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 预览定时任务
      tags:
      - 定时任务
  /tasks/{id}/run:
    post:
      consumes:
      - application/json
      description: 立即执行指定ID的定时任务，不等待下一个调度时间
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: string
      - description: 执行选项
        in: body
        name: request
        schema:
          $ref: '#/definitions/handlers.RunTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 任务已开始执行或预览结果
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 任务不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 立即执行定时任务
      tags:
      - 定时任务
  /tasks/{id}/toggle:
    post:
      consumes:
      - application/json
      description: 切换定时任务的启用状态
      parameters:
      - description: 任务ID
        in: path
        name: id
        required: true
        type: string
      - description: 是否启用
        in: query
        name: enabled
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 状态更新成功
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 任务不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 启用或禁用定时任务
      tags:
      - 定时任务
schemes:
- http
- https
swagger: "2.0"
